imageList = {
  'images/09DuoCindlogo.jpg': 'Cinderella',
  'images/robinhoodNEW2008logo.gif': 'Robin Hood',
  'images/nppcindlow.jpg': 'Cinderella',
  'images/CambLogoNew.jpg': 'Cinderella',
  'images/ChelmsfordLogo07.jpg': 'Jack and the Beanstalk',
  'images/hammondbeautylogo.jpg': 'Sleeping Beauty',
  'images/BeautyLogoNots09.jpg': 'Beauty and the Beast',
  'images/SloughLogo07.jpg': 'Aladdin',
  'images/07GlasgowPavilion_logo.jpg': 'Cinderella',
  'images/07MillfordLogo2.jpg': 'Peter Pan',
  'images/07NorthHykehamlogo.jpg': 'Jack and the Beanstalk',
  'images/08BasildonLogo.jpg': 'Cinderella',
  'images/08HitchinKids.jpg': 'Quibble & Squabbles Magical Christmas Eve',
  'images/09CarlisleLogo.jpg': 'Dick Whittington and the Pirate Adventure',
  'images/09Fernehamlogo.jpg': 'Snow White',
  'images/09Northlogo.jpg': 'Peter Pan',
  'images/AldershotB&Beast-title.jpg': 'Beauty and the Beast',
  'images/AldershotLogoPan.jpg': 'Peter Pan',
  'images/ByreLogoMG.jpg': 'Mother Goose',
  'images/CamberleyPanLogo.jpg': 'Peter Pan',
  'images/Capitol-ppan-logo-green-sma.jpg': 'Peter Pan',
  'images/Chelmsfordlogo09.jpg': 'Jack and the Beanstalk',
  'images/ConsettLogo07_small.jpg': 'Aladdin',
  'images/DWLogoCamberleyTheatre.jpg': 'Dick Whittington',
  'images/HBPussBootslogo.jpg': 'Puss in Bots',
  'images/HolmanSWLogo-2.jpg': 'Snow White',
  'images/HorshamLogo09.jpg': 'Cinderella',
  'images/Kids-show-logo.jpg': 'The Emerors New Clothes',
  'images/OwenMoneyPanLogo.jpg': 'Peter Pan',
  'images/PPLogo_new.jpg': 'Peter Pan',
  'images/SWLogo-Stockport-Plaza.jpg': 'Show White',
  'images/Sinbad%20Logo.jpg': 'Sinbad',
  'images/SouthLogo09.jpg': 'Santa Claus and the return of Jack Frost',
  'images/UKPRobinHoodLogo_new.jpg': 'Robin Hood and the Babes in the Wood',
  'images/WISHdiclogo.jpg': 'Dick Whittington',
  'images/aldershotwizlogo.jpg': 'The Wizard of Oz',
  'images/bath_panto_logo.jpg': 'Robin Hood and the Babes in the Wood',
  'images/beauty_artwork.jpg': 'Beauty and the Beast',
  'images/brightonozlogo.jpg': 'The Wizard of Oz',
  'images/camb08hi-res-logo.jpg': 'Jack and the Beanstalk',
  'images/cambridgediclogo.jpg': 'Dick Whittington',
  'images/carlisle07words.jpg': 'Snow White',
  'images/chennailogo2007.jpg': 'Pirates of the Curried Beans',
  'images/goldilocksqdoslogo.gif': 'Goldilocks and the 3 bears',
  'images/hammondpanlogo.jpg': 'Peter Pan',
  'images/keydiclogo.jpg': 'Dick Whittington and His Cat',
  'images/littlemermaidNEW_temp.jpg': 'The Little Mermaid and the Pirates',
  'images/millfieldlogo09.jpg': 'Aladdin',
  'images/npp-beautyweb.jpg': 'Sleeping Beauty',
  'images/nppaladweb.jpg': 'Aladdin',
  'images/nppswweb.jpg': 'Snow White and the Seven Dwarfs',
  'images/pussinbootssmall.jpg': 'Puss in Boots',
  'images/rhyl_panto_logo.jpg': 'Jack and the Beanstalk',
  'images/robinsoncrusoeNEW2008logo.gif': 'Robinson Crusoe',
  'images/santawinterwonderlan.jpg': 'Winter Wonderland',
  'images/sheffield_panto_logo.jpg': 'Dick Whittington',
  'images/south08logo.jpg': 'Cinderella',
  'images/tamesidehippodrime.gif': '',
  'images/windsorlogo08.jpg': 'Peter Pan',
}
shortCuts = [
    ("aladdin","Aladdin"),
    ("batb","Beauty and the Beast"),
    ("cinder","Cinderella"),
    ("dick","Dick Whittington"),
    ("beanstalk","Jack and the Beanstalk"),
    ("jack","Jack and the Beanstalk"),
    ("goose","Mother Goose"),
    ("peter","Peter Pan"),
    ("sleep","Sleeping Beauty"),
    ("snow","Snow White"),
    ("wizard","The Wizard of Oz"),
    ]
def getTitleOfImage(img):
  if img in imageList:
    return imageList[img]
  img = img.lower()
  for i in shortCuts:
    if i[0] in img:
      return i[1]
