imageList = {
  'images/WISHAladdinlogo.jpg': 'Aladdin',
  'images/HBCinderellaLogo.jpg': 'Cinderella',
  'images/snowwhiteNEW2008logo.gif': 'Snow White',
  'images/cinderellaffelogo.jpg': 'Cinderella',
  'images/WishSleepingBeautyLogo_new.jpg': 'Sleeping Beauty',
  'images/peterpanhastings.jpg': 'Peter Pan',
  'images/hisssleepingbeauty.jpg': 'SleepingBeauty',
  'images/FFECinders_new.jpg': 'Cinderella',
  'images/aladdinNEW2008logo.gif': 'Aladdin',
  'images/MillfieldCinderella08rgb.jpg': 'Cinderella',
  'images/09EvolPeterPanLogo.jpg': 'Peter Pan',
  'images/HBJackLogo_colour.jpg': 'Jack and the Beanstalk',
  'images/FFEPeterPan_new.jpg': 'Peter Pan',
  'images/HolmanCinderslogo.jpg': 'Cinderella',
  'images/09DuoCindlogo.jpg': 'Cinderella',
  'images/ffesleepingbeauty09.jpg': 'Sleeping Beauty',
  'images/nppjackweb.jpg': 'Jack and the Beanstalk',
  'images/WishCinderellaLogo.jpg': 'Cinderella',
  'images/aladdin2007.gif': 'Aladdin',
  'images/mothergooseNEW2008logo.gif': 'Mother Goose',
  'images/robinhoodNEW2008logo.gif': 'Robin Hood',
  'images/windsoraladdinlogo09.jpg': 'Aladdin',
  'images/PHA_Jack--Bean_logo.jpg': 'Jack and the Beanstalk',
  'images/peterpanNEW2008logo.gif': 'Peter Pan',
  'images/EvoSnowWhite-3.jpg': 'Snow White',
  'images/dickwhittingtonshieldcr8.jpg': 'Dick Whittington',
  'images/mothergooselogoliverpool.jpg': 'Mother Goose',
  'images/cinderella_title.jpg': 'Cinderella',
  'images/FFEDickWhitt_new.jpg': 'Dick Whittington',
  'images/EvolutionCindersLogo.jpg': 'Cinderella',
  'images/aladdinffelogo.jpg': 'Aladdin',
  'images/Snow_white_logocleethorpes.jpg': 'Snow White',
  'images/09DuoSnowlogo.jpg': 'Snow White',
  'images/nppcindlow.jpg': 'Cinderella',
  'images/ukpCinderellaLogo_news.jpg': 'Cinderella',
  'images/Cinderella_harlowlogo.jpg': 'Cinderella',
  'images/snow_whiteffelogo.jpg': 'Snow White',
  'images/snowwhite_canterbury.jpg': 'Snow White',
  'images/ukpAladdinLogo_new.jpg': 'Aladdin',
  'images/HBCinderella_logo.jpg': 'Cinderella',
  'images/ukpSnowWhiteLogo_news.jpg': 'Snow White',
  'images/redmondsnow.jpg': 'Snow White',
  'images/HissBooAladdinLogo.jpg': 'Aladdin',
  'images/CinderellaWarwicklogo.jpg': 'Cinderella',
  'images/cinderellaNEW2008logo.gif': 'Cinderella',
  'images/prestoncinderellatext.jpg': 'Cinderella',
  'images/09WimbAladdin.jpg': 'Aladdin',
  'images/EvolutionAladdinLogo.jpg': 'Aladdin',
  'images/ybrcinderella.jpg': 'Cinderella',
  'images/HBDickWhittLogo.jpg': 'Dick Whittington',
  'images/Jacklogoipswich09.jpg': 'Jack and the Beanstalk',
  'images/EvolutionJacklogo.jpg': 'Jack and the Beanstalk',
  'images/DickWhittextCoch.jpg': 'Dick Whittington',
  'images/WISHJacklogo.jpg': 'Jack and the Beanstalk',
  'images/dickwhittingtonNEW2008logo.gif': 'Dick Whittington',
  'images/HBJackLogo.jpg': 'Jack and the Beanstalk',
  'images/Dick_WhittYeovil09.jpg': 'Dick Whittington',
  'images/BrightonJackLogo.jpg': 'Jack and the Beanstalk',
  'images/motherwelllogojack09.jpg': 'Jack and the Beanstalk',
  'images/jackNEW2008logo.gif': 'Jack and the Beanstalk',
}
